name: Sync master to TesteAutomatizado

on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
            git config user.name "Arthur Rocco"
            git config user.email "arthurbrocco@gmail.com"

      - name: Merge master into TesteAutomatizado
        run: |
            git fetch origin
            git checkout TesteAutomatizado
            git merge master
            git push origin TesteAutomatizado
